services:
  langdon:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.langdon
      tags:
        - langdon_i
    container_name: langdon_cli_c
    stdin_open: true
    tty: true
    networks:
      - recon_network
    depends_on:
      - tor

  tor:
    build:
      dockerfile: Dockerfile.tor
      tags:
        - tor_i
    container_name: langdon_tor_c
    networks:
      - recon_network

networks:
  recon_network:
    driver: bridge
