services:
  langdon:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.langdon
      tags:
        - langdon_i
    container_name: langdon_cli_c
    stdin_open: true
    tty: true
    networks:
      - recon_network
    volumes:
      - recon_volume:/recon
    depends_on:
      - tor

  langdonguibe:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.langdon
      tags:
        - langdon_i
    volumes:
      - recon_volume:/recon
    command:
      [
        "/root/.local/bin/poetry",
        "--project",
        "/root/langdon",
        "--directory",
        "/recon",
        "run",
        "gunicorn",
        "--bind",
        "0.0.0.0:5000",
        "--access-logfile",
        "/dev/stdout",
        "--error-logfile",
        "/dev/stderr",
        "langdongui.app:app",
      ]
    networks:
      - gui_network

  langdonguife:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.langdongui.frontend
      tags:
        - langdonguife_i
    depends_on:
      - langdonguibe
    ports:
      - "8080:80"
    networks:
      - gui_network

  tor:
    build:
      dockerfile: Dockerfile.tor
      tags:
        - tor_i
    container_name: langdon_tor_c
    networks:
      - recon_network

networks:
  recon_network:
    driver: bridge
  gui_network:
    driver: bridge

volumes:
  recon_volume:
